# -*- coding: utf-8 -*-
"""simple_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_hdWi7YzEpF_m7fJ1q3upiZsJ8kbcJo
"""

#Standard DNA codon table (DNA codons to amino acid one-letter codes)
CODON_TABLE = {
    #phenylalanine
    "TTT":"F","TTC":"F",
    #Leucine
    "TTA":"L","TTG":"L","CTT":"L","CTC":"L","CTA":"L","CTG":"L",
    #Isoleucine
    "ATT":"I","ATC":"I","ATA":"I",
    #Methionine (start)
    "ATG":"M",
    #Valine
    "GTT":"V","GTC":"V","GTA":"V","GTG":"V",
    # Serine
    "TCT":"S","TCC":"S","TCA":"S","TCG":"S","AGT":"S","AGC":"S",
    # Proline
    "CCT":"P","CCC":"P","CCA":"P","CCG":"P",
    # Threonine
    "ACT":"T","ACC":"T","ACA":"T","ACG":"T",
    # Alanine
    "GCT":"A","GCC":"A","GCA":"A","GCG":"A",
    # Tyrosine
    "TAT":"Y","TAC":"Y",
    # Histidine
    "CAT":"H","CAC":"H",
    # Glutamine
    "CAA":"Q","CAG":"Q",
    # Asparagine
    "AAT":"N","AAC":"N",
    # Lysine
    "AAA":"K","AAG":"K",
    # Aspartic acid
    "GAT":"D","GAC":"D",
    # Glutamic acid
    "GAA":"E","GAG":"E",
    # Cysteine
    "TGT":"C","TGC":"C",
    # Tryptophan
    "TGG":"W",
    # Arginine
    "CGT":"R","CGC":"R","CGA":"R","CGG":"R","AGA":"R","AGG":"R",
    # Glycine
    "GGT":"G","GGC":"G","GGA":"G","GGG":"G",
    # Stop codons
    "TAA":"*","TAG":"*","TGA":"*"
}

def translate_dna(dna_seq, frame=0, to_stop=True):
  """
  Translate a DNA sequence into a protein sequence.

  parameters:
  dna_seq(str): DNA sequence (A,T,G,C). Lowercase allowed.
  frame (int): 0,1,or 2 - translation reading frame.
  to_stop (bool): if True, translation stops at first stop codon(not included)
                  if False, stop codons are translated as '*'
                   Returns:
      protein (str): translated amino acid sequence (one-letter codes)
  """
  #1. Clean Input
  seq = dna_seq.upper().replace("\n", "").replace(" ", "")
  #2. Simple Validation (warn on bad chars)
  for ch in seq:
    if ch not in "ATGCN":
      raise ValueError(f"Invalid base '{ch} in DNA sequence. Allowed: A,T,G,C,N")
  protein = []
  #3. Walk through sequence by codon
  for i in range(frame, len(seq)- 2,3):
    codon = seq[i:i+3]
    #convert codon with 'N' (unknown) to X if not determinable
    if "N" in codon:
      aa= "x"
    else:
      aa= CODON_TABLE.get(codon, "x") # unknown codon to X
      if aa== "*":
        if to_stop:
          break
        else:
          protein.append("*")
      else:
        protein.append(aa)
  return "".join(protein)

#Task 1: short sequence that ends in a stop codon
print(translate_dna("ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG", frame=0, to_stop=True))

#2: Simple sequence
print(translate_dna("ATGGCC",frame=0))

def hamming_distance(str1, str2):
    # Make both strings the same length by padding the shorter one with spaces
    max_len = max(len(str1), len(str2))
    str1 = str1.ljust(max_len)
    str2 = str2.ljust(max_len)

    # Compare each character in both strings
    distance = 0
    for c1, c2 in zip(str1, str2):
        if c1 != c2:
            distance += 1
    return distance

slack_username = "Antara Ghanta"
twitter_handle = "antara_ghanta"

result = hamming_distance(slack_username, twitter_handle)
print("The Hamming distance is:", result)

